logging:
  level:
    # Application debug logging
    '[com.example.bank]': DEBUG

    # Log Spring Data SQL queries and parameters
    #'[org.hibernate.SQL]': DEBUG
    #'[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE

    # Disable deprecated WARNING logging
    '[org.springframework.core.LocalVariableTableParameterNameDiscoverer]': OFF

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
